// debug-modal.js (FROM-SCRATCH IMPLEMENTATION)

// Since we don't have the real helper files, we define simplified,
// placeholder versions of the constants and functions that this module needs.
const LINGUISTIC_STYLES = ['auto', 'casual', 'witty', 'playful', 'direct', 'intellectual', 'poetic', 'charming', 'sarcastic', 'sexual', 'mysterious'];
const DATE_ARC_PHASES = ['rapport', 'attraction', 'escalation', 'planning', 'post_date'];
const CONVERSATION_STATES = ['OPENER', 'EARLY_CONVO', 'ACTIVE_CONVO', 'REENGAGING_DAY', 'REENGAGING_WEEK', 'REENGAGING_MONTH'];
const INTENT_OPTIONS = ['questioning', 'planning', 'reacting_to_humor', 'storytelling', 'flirting_or_sexual'];


/**
 * FROM-SCRATCH-BEST-EFFORT
 * This is the core logic for the debug modal. It takes all the data
 * and generates the prompts that would be sent to the AI.
 */
function generatePrompts(data) {
    const systemMessage = `You are Wingman AI. Your goal is to help the user write a message to their match, ${data.theirName}.

// -- This prompt was generated by the from-scratch debug modal -- //

User's Profile:
${data.myProfile}

Match's Profile:
${data.theirProfile}

Conversation Analysis:
${JSON.stringify(data.conversationAnalysis, null, 2)}

Task Instructions:
${JSON.stringify(data.taskInstructions, null, 2)}`;

    const userMessage = `Generate a message based on the provided context and instructions. The user's primary goal is: "${data.taskInstructions.goal}".`;

    return { systemMessage, userMessage };
}


// --- The rest of this file is boilerplate UI code adapted from the reference file ---
// --- It builds the modal, but the core logic is the generatePrompts function above ---

let modalState = {};
let callbacks = {};
let currentView = 'analysis';
const VIEWS = ['analysis', 'memory', 'context', 'final'];

function setNestedValue(obj, path, value) {
    const keys = path.split('.');
    let current = obj;
    for (let i = 0; i < keys.length - 1; i++) {
        if (current[keys[i]] === undefined) current[keys[i]] = {};
        current = current[keys[i]];
    }
    current[keys[keys.length - 1]] = value;
}

function createSelect(id, dataPath, options, selectedValue) {
    const optionsHtml = options.map(opt => `<option value="${opt}" ${opt === selectedValue ? 'selected' : ''}>${opt.charAt(0).toUpperCase() + opt.slice(1)}</option>`).join('');
    return `<select id="${id}" data-path="${dataPath}" class="modal-input">${optionsHtml}</select>`;
}

function createMultiSelect(id, dataPath, allOptions, selectedOptions) {
    const selectedSet = new Set(selectedOptions || []);
    const optionsHtml = allOptions.map(opt => `<option value="${opt}" ${selectedSet.has(opt) ? 'selected' : ''}>${opt.charAt(0).toUpperCase() + opt.slice(1)}</option>`).join('');
    return `<select id="${id}" data-path="${dataPath}" class="modal-input" multiple>${optionsHtml}</select>`;
}

function createTextarea(id, dataPath, value) {
    return `<textarea id="${id}" data-path="${dataPath}" class="modal-input">${value || ''}</textarea>`;
}

function createCheckbox(id, dataPath, checked) {
    return `<input type="checkbox" id="${id}" data-path="${dataPath}" ${checked ? 'checked' : ''} class="modal-input">`;
}

function createSlider(id, dataPath, value, min, max, step) {
    return `<div class="slider-container"><input type="range" id="${id}" data-path="${dataPath}" value="${value}" min="${min}" max="${max}" step="${step}"><span id="${id}-value" class="value-display">${value}</span></div>`;
}

function renderView() {
    const contentEl = document.getElementById('debug-modal-content');
    if (!contentEl) return;

    let html = '';
    switch (currentView) {
        case 'analysis': html = renderAnalysisView(); break;
        case 'memory': html = renderMemoryView(); break;
        case 'context': html = renderContextView(); break;
        case 'final': html = renderFinalPayloadView(); break;
    }
    contentEl.innerHTML = html;
    attachEventListeners();
}

function renderAnalysisView() {
    const { conversationAnalysis } = modalState;
    const { lastMessageAnalysis } = conversationAnalysis;
    return `<h3>View 1: Conversation Analysis</h3>
        <table class="payload-table">
            <tr><td>Conversation State</td><td>${createSelect('analysis-state', 'conversationAnalysis.conversationState', CONVERSATION_STATES, conversationAnalysis.conversationState)}</td></tr>
            <tr><td colspan="2"><strong>Last Message Subtext</strong></td></tr>
            <tr><td>Is Direct Question?</td><td>${createCheckbox('subtext-isDirectQuestion', 'conversationAnalysis.lastMessageAnalysis.isDirectQuestion', lastMessageAnalysis.isDirectQuestion)}</td></tr>
            <tr><td>Valence</td><td>${createSlider('subtext-valence', 'conversationAnalysis.lastMessageAnalysis.valence', lastMessageAnalysis.valence, -1, 1, 0.1)}</td></tr>
            <tr><td>Intents</td><td>${createMultiSelect('subtext-intents', 'conversationAnalysis.lastMessageAnalysis.intents', INTENT_OPTIONS, lastMessageAnalysis.intents)}</td></tr>
        </table>`;
}

function renderMemoryView() {
    const { memory } = modalState.conversationAnalysis;
    return `<h3>View 2: Match Memory</h3>
        <table class="payload-table">
            <tr><td>Date Arc Phase</td><td>${createSelect('memory-dateArcPhase', 'conversationAnalysis.memory.dateArcPhase', DATE_ARC_PHASES, memory.dateArcPhase)}</td></tr>
            <tr><td>Inside Jokes</td><td>${createTextarea('memory-insideJokes', 'conversationAnalysis.memory.insideJokes', (memory.insideJokes || []).join('\\n'))}</td></tr>
        </table>`;
}

function renderContextView() {
    return `<h3>View 3: Profiles & History</h3>
        <table class="payload-table">
            <tr><td>My Profile</td><td>${createTextarea('context-myProfile', 'myProfile', modalState.myProfile)}</td></tr>
            <tr><td>Their Profile</td><td>${createTextarea('context-theirProfile', 'theirProfile', modalState.theirProfile)}</td></tr>
        </table>`;
}

function renderFinalPayloadView() {
    const { systemMessage, userMessage } = generatePrompts(modalState);
    modalState.finalPayload = { messages: [{ role: "system", content: systemMessage }, { role: "user", content: userMessage }], temperature: modalState.taskInstructions.temperature };
    return `<h3>View 4: Final Payload Review</h3>
        <div class="messages-container">
            <div class="message-card"><div class="message-card-header"><strong>System Message</strong></div><div class="message-card-content">${createTextarea('final-system', 'finalPayload.messages.0.content', systemMessage)}</div></div>
            <div class="message-card"><div class="message-card-header"><strong>User Message</strong></div><div class="message-card-content">${createTextarea('final-user', 'finalPayload.messages.1.content', userMessage)}</div></div>
        </div>`;
}

function updateStateFromUI(e) {
    const el = e.target;
    const path = el.dataset.path;
    if (!path) return;
    let value = el.type === 'checkbox' ? el.checked : (el.type === 'range' || el.type === 'number') ? parseFloat(el.value) : el.value;
    if (el.multiple) value = Array.from(el.selectedOptions).map(opt => opt.value);
    if (path.endsWith('insideJokes')) value = el.value.split('\\n').filter(Boolean);
    setNestedValue(modalState, path, value);
}

function attachEventListeners() {
    const contentEl = document.getElementById('debug-modal-content');
    contentEl.addEventListener('input', updateStateFromUI);
    contentEl.querySelectorAll('input[type="range"]').forEach(slider => {
        const valueDisplay = document.getElementById(`${slider.id}-value`);
        if (valueDisplay) valueDisplay.textContent = slider.value;
    });
}

function handleNav(direction) {
    const currentIndex = VIEWS.indexOf(currentView);
    let nextIndex = currentIndex + direction;
    if (nextIndex < 0 || nextIndex >= VIEWS.length) return;
    currentView = VIEWS[nextIndex];
    renderView();
    updateNavButtons();
}

function updateNavButtons() {
    const currentIndex = VIEWS.indexOf(currentView);
    document.getElementById('modal-back-btn').disabled = currentIndex === 0;
    const primaryBtn = document.getElementById('modal-primary-action-btn');
    primaryBtn.textContent = (currentIndex === VIEWS.length - 1) ? 'Send to AI' : 'Next';
}

export function showNlpModal(initialData, cbs) {
    callbacks = cbs;
    modalState = JSON.parse(JSON.stringify(initialData));
    currentView = 'analysis';

    const overlay = document.getElementById('debug-modal-overlay');
    overlay.innerHTML = `<div class="modal">
            <div class="modal-header">Debug & Override Mode</div>
            <div class="modal-content" id="debug-modal-content"></div>
            <div class="modal-footer"><div class="modal-actions">
                <button id="modal-cancel-btn" class="btn btn-secondary">Cancel</button>
                <button id="modal-back-btn" class="btn btn-secondary">Back</button>
                <button id="modal-primary-action-btn" class="btn btn-primary">Next</button>
            </div></div></div>`;
    overlay.classList.remove('hidden');

    document.getElementById('modal-cancel-btn').addEventListener('click', callbacks.hideDebugModal);
    document.getElementById('modal-back-btn').addEventListener('click', () => handleNav(-1));
    document.getElementById('modal-primary-action-btn').addEventListener('click', () => {
        if (currentView === 'final') {
            callbacks.setUIGeneratingState(true);
            callbacks.startTimer(Date.now());
            callbacks.hideDebugModal();
            callbacks.sendFinalPayloadToAI(modalState.finalPayload);
        } else {
            handleNav(1);
        }
    });

    renderView();
    updateNavButtons();
}

export function hideDebugModal() {
    const overlay = document.getElementById('debug-modal-overlay');
    if (overlay) {
        overlay.classList.add('hidden');
        overlay.innerHTML = '';
    }
}
